services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      TZ: ${TZ:-America/Sao_Paulo}
      PGTZ: ${PGTZ:-America/Sao_Paulo}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    command: postgres -c timezone=${TZ:-America/Sao_Paulo}
    container_name: "postgres"
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"

