export const modalStyles = {
  host: 'contents',
  dialog: [
    'm-auto',
    'w-(--modal-width,calc(100%-2rem))',
    'max-w-none',
    'max-h-[calc(100dvh-2rem)]',
    'overflow-auto',
    'border',
    'border-border',
    'rounded-md',
    'bg-background-2',
    'p-0',
    'text-foreground',
    'opacity-0',
    'translate-y-12',
    'shadow-[0_1.5rem_4rem_rgb(0_0_0/35%)]',
    'transition-[opacity,translate,overlay,display]',
    'transition-discrete',
    'duration-250',
    'ease-[ease]',
    'open:translate-y-0',
    'open:opacity-100',
    'starting:open:translate-y-12',
    'starting:open:opacity-0',
    'backdrop:bg-gray-900/90',
    'dark:backdrop:bg-black/80',
    'backdrop:backdrop-blur-[2px]',
    'backdrop:opacity-0',
    'backdrop:transition-[opacity,overlay,display]',
    'backdrop:transition-discrete',
    'backdrop:duration-250',
    'backdrop:ease-[ease]',
    'open:backdrop:opacity-100',
    'starting:open:backdrop:opacity-0',
    'sm:w-(--modal-width,80%)',
    'md:w-(--modal-width,70%)',
    'lg:w-(--modal-width,60%)',
    'xl:w-(--modal-width,50%)',
    '2xl:w-(--modal-width,40%)',
    'motion-reduce:duration-[0.01ms]',
    'motion-reduce:backdrop:duration-[0.01ms]',
  ].join(' '),
  content: 'w-full',
} as const;
