export const usuariosStyles = {
  host: 'block h-full min-h-0',
  page: 'mx-auto flex h-full min-h-0 w-full max-w-7xl flex-col gap-6 p-4 sm:p-6 lg:p-8',
  header: 'flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between',
  title: 'text-2xl font-bold text-primary-text',
  subtitle: 'mt-1 text-sm text-foreground/75',
  filters: 'grid gap-4 border-y border-border/35 bg-background-2/50 px-4 py-4 sm:grid-cols-2 lg:max-w-2xl',
  gridSection: 'flex min-h-0 min-w-0 flex-1 flex-col',
  tableWrapper: 'min-h-0 flex-1 overflow-auto border border-border/40 bg-background',
  table: 'w-full min-w-180 border-collapse text-left text-sm',
  th: 'sticky top-0 z-10 border-b border-border/40 bg-background-2 px-4 py-3 font-semibold text-primary-text',
  actionsTh: 'sticky top-0 z-10 w-28 border-b border-border/40 bg-background-2 px-4 py-3 text-center font-semibold text-primary-text',
  sortButton: 'font-semibold text-primary-text hover:text-primary',
  sortContent: 'inline-flex items-center gap-1.5 whitespace-nowrap',
  sortIndicator: 'inline-flex min-w-2.5 justify-center text-xs font-bold text-primary',
  row: 'border-b border-border/25 last:border-b-0 hover:bg-background-2/55',
  td: 'px-4 py-3 text-foreground',
  nameCell: 'px-4 py-3 font-semibold text-primary-text',
  stateCell: 'px-4 py-12 text-center text-foreground/70',
  activeBadge: 'inline-flex rounded-full bg-success/15 px-2.5 py-1 text-xs font-semibold text-success',
  inactiveBadge: 'inline-flex rounded-full bg-warning/15 px-2.5 py-1 text-xs font-semibold text-foreground',
  actionsCell: 'flex h-14 items-center justify-center gap-1 px-4',
  iconButton: 'size-9 rounded-md text-primary hover:bg-primary/10',
  deleteIconButton: 'size-9 rounded-md text-danger hover:bg-danger/10',
  pagination: [
    'grid shrink-0 grid-cols-1 items-center justify-items-center gap-3 border-x border-b border-border/40 px-4 py-3',
    'sm:grid-cols-[1fr_auto_1fr]',
  ].join(' '),
  resultCount: 'text-sm text-foreground/75 sm:justify-self-start',
  pageControls: 'flex items-center justify-center gap-1 whitespace-nowrap',
  pageButton: 'min-h-8 min-w-8 px-2 text-sm text-foreground hover:text-primary',
  currentPageButton: 'min-h-8 min-w-8 px-2 text-sm font-bold text-primary underline underline-offset-4',
  pageSize: 'w-40 sm:justify-self-end',
  confirmation: 'flex flex-col gap-4 p-5 sm:p-6',
  confirmationTitle: 'text-xl font-bold text-primary-text',
  confirmationActions: 'flex justify-end gap-3 border-t border-border/40 pt-4',
} as const;
