export const dataTableStyles = {
  host: 'block min-w-0',
  container: 'w-full overflow-hidden rounded-md border border-border bg-background-2 text-foreground',
  loadingContainer: 'flex min-h-48 items-center justify-center p-6',
  loadingContent: 'flex flex-col items-center gap-3 text-center',
  loadingSpinner: [
    'size-9 animate-spin rounded-full border-4 border-border border-t-primary',
    'motion-reduce:animate-none',
  ].join(' '),
  loadingText: 'text-sm font-medium',
  tableContainer: 'w-full overflow-x-auto',
  table: 'w-full border-collapse text-left text-sm',
  header: 'bg-background',
  headerRow: 'border-b border-border',
  headerCell: 'min-w-32 px-4 py-3 align-top font-semibold text-primary-text',
  headerContent: 'flex min-h-6 items-center gap-2',
  headerLabel: 'min-w-0 flex-1',
  sortButton: [
    'inline-flex min-w-0 flex-1 cursor-pointer items-center gap-2 rounded-sm text-left',
    'transition-colors hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
  ].join(' '),
  sortIcon: 'shrink-0 text-xs text-foreground',
  filterContainer: 'mt-2 flex items-center gap-1',
  filterControl: [
    'min-w-28 flex-1 rounded-md border border-border bg-background px-2 py-1.5 text-sm text-primary-text',
    'outline-none transition-colors placeholder:text-foreground/60',
    'focus:border-primary focus:ring-2 focus:ring-primary/25',
  ].join(' '),
  clearFilterButton: [
    'inline-flex size-7 shrink-0 cursor-pointer items-center justify-center rounded-md text-foreground',
    'transition-colors hover:bg-background-2 hover:text-danger',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
  ].join(' '),
  body: 'divide-y divide-border',
  bodyRow: 'transition-colors hover:bg-background',
  clickableRow: 'cursor-pointer',
  bodyCell: 'px-4 py-3 align-middle',
  emptyCell: 'px-4 py-12 text-center text-foreground/75',
  footer: [
    'flex flex-col gap-3 border-t border-border bg-background px-4 py-3',
    'lg:flex-row lg:items-center lg:justify-between',
  ].join(' '),
  summary: 'text-sm text-foreground',
  pagination: 'flex flex-wrap items-center gap-3',
  fieldGroup: 'flex items-center gap-2',
  fieldLabel: 'text-sm text-foreground',
  select: [
    'rounded-md border border-border bg-background px-2 py-1.5 text-sm text-primary-text',
    'outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/25',
  ].join(' '),
  pageInput: [
    'w-16 rounded-md border border-border bg-background px-2 py-1.5 text-center text-sm text-primary-text',
    'outline-none transition-colors focus:border-primary focus:ring-2 focus:ring-primary/25',
  ].join(' '),
  pageStatus: 'whitespace-nowrap text-sm text-foreground',
  paginationButton: [
    'rounded-md border border-border bg-background px-3 py-1.5 text-sm text-primary-text',
    'transition-colors hover:bg-background-2',
  ].join(' '),
} as const;
