export const dataTableStyles = {
  host: 'block h-full min-h-0',
  container: 'flex h-full min-h-0 flex-col overflow-hidden border border-border/40 bg-background',
  tableContainer: 'min-h-0 flex-1 overflow-auto',
  table: 'w-full min-w-180 border-collapse text-left text-sm',
  header: 'sticky top-0 z-10 bg-background-2',
  headerCell: 'border-b border-border/40 px-4 py-3 font-semibold text-primary-text',
  headerContent: 'flex min-w-0 items-center gap-1.5',
  sortButton: [
    'inline-flex min-w-0 cursor-pointer items-center gap-1.5 whitespace-nowrap text-left',
    'font-semibold text-primary-text hover:text-primary disabled:cursor-default disabled:hover:text-primary-text',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
  ].join(' '),
  sortIcon: 'inline-flex w-3 shrink-0 justify-center text-xs text-primary',
  filterButton: [
    'inline-flex size-7 shrink-0 cursor-pointer items-center justify-center rounded-md text-xs',
    'text-foreground/55 hover:bg-background hover:text-primary',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary',
  ].join(' '),
  activeFilterButton: 'bg-primary/10 text-primary',
  filterPanel: 'flex min-w-56 flex-col gap-3 p-1',
  filterLabel: 'text-sm font-semibold text-primary-text',
  filterInput: [
    'w-full rounded-md bg-background px-3 py-2 text-sm text-foreground ring-2 ring-border outline-none',
    'placeholder:text-foreground/55 focus:ring-primary',
  ].join(' '),
  filterActions: 'flex justify-end',
  clearFilter: 'cursor-pointer text-sm font-medium text-primary hover:text-tertiary',
  row: 'border-b border-border/25 last:border-b-0 hover:bg-background-2/55',
  cell: 'max-w-0 overflow-hidden px-4 py-3 text-ellipsis whitespace-nowrap text-foreground',
  stateCell: 'px-4 py-12 text-center text-foreground/70',
  footer: [
    'grid shrink-0 grid-cols-1 items-center justify-items-center gap-3 border-t border-border/40 px-4 py-3',
    'sm:grid-cols-[1fr_auto_1fr]',
  ].join(' '),
  resultCount: 'text-sm text-foreground/75 sm:justify-self-start',
  pageControls: 'flex items-center justify-center gap-1 whitespace-nowrap',
  pageButton: 'min-h-8 min-w-8 cursor-pointer px-2 text-sm text-foreground hover:text-primary disabled:cursor-default disabled:opacity-35',
  currentPageButton: 'min-h-8 min-w-8 px-2 text-sm font-bold text-primary underline underline-offset-4',
  pageSize: 'flex items-center gap-2 sm:justify-self-end',
  pageSizeLabel: 'hidden text-sm text-foreground/75 lg:inline',
  pageSizeSelect: [
    'rounded-md bg-background px-3 py-1.5 text-sm text-foreground ring-1 ring-border outline-none',
    'focus:ring-2 focus:ring-primary',
  ].join(' '),
} as const;
