export const loginStyles = {
  host: 'block',
  page: 'grid min-h-dvh place-items-center bg-background px-4 py-8 text-foreground',
  card: 'flex w-full max-w-136 flex-col items-center',
  brand: 'inline-flex items-center gap-3 text-2xl font-bold text-primary-text',
  brandMark: [
    'grid size-17 place-items-center rounded-full',
    'bg-primary text-[2rem] text-white italic',
    'shadow-[inset_-0.35rem_-0.35rem_0_rgb(0_0_0/10%)]',
  ].join(' '),
  title: 'mt-8 mb-6 text-[clamp(1.5rem,4vw,2rem)] font-bold text-primary-text',
  form: 'flex w-full flex-col gap-4',
  field: 'grid gap-[0.4rem]',
  label: 'text-sm font-semibold text-foreground',
  input: [
    'min-h-11 w-full rounded-md border-2 border-border bg-background-2 px-[0.9rem] py-[0.6rem]',
    'text-foreground outline-none placeholder:text-foreground/60',
    'transition-colors duration-160 ease-[ease]',
    'hover:border-primary focus:border-secondary',
  ].join(' '),
  validationError: 'text-sm text-danger',
  rememberOption: 'flex cursor-pointer items-center gap-2 self-center text-sm text-foreground',
  rememberInput: 'accent-secondary',
  signupLink: 'mt-6 text-[0.9rem]',
} as const;
