import type { Metadata } from "next";
import "./globals.css";
import App from "./App";
import { DarkModeProvider } from "@/contexts/darkMode/DarkModeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR" className={htmlTailwindClass}>
      <body className={bodyTailwindClass}>
        <DarkModeProvider>
          <App>
            {children} {/*posteriormente encapsular children com a provider do contexto do usuario*/}
          </App>
        </DarkModeProvider>
      </body>
    </html>
  );
}

const htmlTailwindClass = `
  flex 
  flex-col 
  h-full
`;

const bodyTailwindClass = `
  dark
  flex
  flex-col 
  h-full
  bg-white dark:bg-gray-900 
  text-gray-900 dark:text-white
  transition-colors duration-300
`;