import type { Metadata } from "next";
import "./globals.css";
import App from "./App";
import darkModeStyles from "./darkModeStyles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  console.log("RootLayout");
  return (
    <html lang="pt-BR" className={htmlTailwindClass}>
      <body className={bodyTailwindClass}>
        <App>
          {children} {/*posteriormente encapsular children com a provider do contexto do usuario*/}
        </App>
      </body>
    </html>
  );
}

const htmlTailwindClass = `
  flex 
  flex-col 
  h-full
  
`;

const bodyTailwindClass = `
  flex 
  flex-col 
  h-full
  ${darkModeStyles.background}
  ${darkModeStyles.texts}
`;