export const pedidoModalStyles = {
  host: 'block',
  content: 'flex max-h-[85vh] flex-col gap-5 overflow-y-auto p-5 sm:p-6',
  header: 'flex flex-col gap-3 border-b border-border/40 pb-4 sm:flex-row sm:items-start sm:justify-between',
  title: 'text-xl font-bold text-primary-text',
  subtitle: 'mt-1 text-sm text-foreground/70',
  draftBadge: 'inline-flex self-start rounded-full bg-foreground/10 px-2.5 py-1 text-xs font-semibold text-foreground',
  pendingBadge: 'inline-flex self-start rounded-full bg-warning/15 px-2.5 py-1 text-xs font-semibold text-warning',
  doneBadge: 'inline-flex self-start rounded-full bg-success/15 px-2.5 py-1 text-xs font-semibold text-success',
  summary: 'grid grid-cols-2 gap-3 rounded-lg bg-background p-4 sm:grid-cols-3',
  summaryItem: 'flex flex-col gap-1',
  summaryLabel: 'text-xs font-medium uppercase tracking-wide text-foreground/60',
  summaryValue: 'font-semibold text-primary-text',
  itemsSection: 'flex flex-col gap-3',
  itemsTitle: 'text-base font-bold text-primary-text',
  state: 'rounded-lg border border-dashed border-border p-8 text-center text-sm text-foreground/65',
  itemsList: 'flex flex-col divide-y divide-border/30 rounded-lg border border-border/40 bg-background',
  item: 'grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 p-3 sm:p-4',
  amount: 'grid size-9 place-items-center rounded-full bg-primary/10 text-sm font-bold text-primary',
  itemInfo: 'min-w-0',
  itemName: 'truncate font-semibold text-primary-text',
  itemUnitPrice: 'mt-0.5 text-xs text-foreground/65',
  itemSubtotal: 'font-semibold text-primary-text',
  total: 'flex items-center justify-between border-t border-border/40 pt-4 text-lg font-bold text-primary-text',
  draftNotice: 'rounded-md bg-foreground/5 px-3 py-2 text-sm text-foreground/70',
  actions: 'flex justify-end gap-3 border-t border-border/40 pt-4',
} as const;
